spring:
  banner:
    location: banner.txt
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:shareit;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS shareit;"
    urlww: "jdbc:h2:./src/shareit;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS shareit;"
    username: test
    password: test
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: shareit
    show-sql: ${JPA_SHOW_SQL:true}
  flyway:
    enabled: true
    validate-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.web-allow-others: true
logging:
  level:
    root: WARN
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG


