server:
  port: 9090
spring:
  banner:
    location: banner.txt
  application:
    name: shareit-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6541/shareit}
    driver-class-name: org.postgresql.Driver
    driver-class-name1: org.h2.Driver
    url11: "jdbc:h2:mem:shareit;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS shareit;"
    urlww: "jdbc:h2:./src/shareit;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS shareit;"
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
    hikari:
      schema: shareit
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: shareit
    show-sql: ${JPA_SHOW_SQL:true}
  flyway:
    enabled: true
    validate-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.web-allow-others: true

logging:
  level:
    root: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG



