
CREATE TABLE shareit.users (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    email varchar NOT NULL,
    CONSTRAINT user_email_uk UNIQUE (email),
    CONSTRAINT user_pk PRIMARY KEY (id)
);

CREATE TABLE shareit.request (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar NOT NULL,
    requestor_user_id int8 NOT NULL,
    created timestamp NULL DEFAULT now(),
    CONSTRAINT request_pk PRIMARY KEY (id),
    CONSTRAINT request_user_fk FOREIGN KEY (requestor_user_id) REFERENCES shareit.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE shareit.item (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    description varchar NULL,
    available bool NOT NULL,
    owner_user_id int8 NOT NULL,
    request_id int8,
    CONSTRAINT item_pk PRIMARY KEY (id),
    CONSTRAINT item_request_fk FOREIGN KEY (request_id) REFERENCES shareit.request(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT item_user_fk FOREIGN KEY (owner_user_id) REFERENCES shareit.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE shareit.booking (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_dt timestamp NOT NULL DEFAULT now(),
    end_dt timestamp NULL,
    item_id int8 NOT NULL,
    booker_user_id int8 NOT NULL,
    status varchar NOT NULL,
    CONSTRAINT booking_pk PRIMARY KEY (id),
    CONSTRAINT booking_item_fk FOREIGN KEY (item_id) REFERENCES shareit.item(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT booking_user_fk FOREIGN KEY (booker_user_id) REFERENCES shareit.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
